/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.mediav.thrift.magic;


import org.apache.thrift.TEnum;

public enum Alphabet implements TEnum {
  A(0),
  B(1);

  private final int value;

  private Alphabet(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Alphabet findByValue(int value) {
    switch (value) {
      case 0:
        return A;
      case 1:
        return B;
      default:
        com.mediav.thrift.EnumUtils.addEnum(Alphabet.class, "$" + value, new Class[]{int.class}, new Object[]{value});
        return Alphabet.valueOf("$" + value);
    }
  }
}
