/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.mediav.thrift.magic;

import org.apache.commons.lang.builder.HashCodeBuilder;

import java.util.*;

public class Basic implements org.apache.thrift.TBase<Basic, Basic._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("XBasic");

  private static final org.apache.thrift.protocol.TField ALPHABET_FIELD_DESC = new org.apache.thrift.protocol.TField("alphabet", org.apache.thrift.protocol.TType.I32, (short)1);

  /**
   * 
   * @see Alphabet
   */
  public Alphabet alphabet;
  public List<com.mediav.thrift.TData> unknownFields;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see Alphabet
     */
    ALPHABET((short)1, "alphabet");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ALPHABET
          return ALPHABET;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ALPHABET, new org.apache.thrift.meta_data.FieldMetaData("alphabet", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, Alphabet.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Basic.class, metaDataMap);
  }

  public Basic() {
  }

  public Basic(
    Alphabet alphabet)
  {
    this();
    this.alphabet = alphabet;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Basic(Basic other) {
    if (other.isSetXAlphabet()) {
      this.alphabet = other.alphabet;
    }
    if (other.unknownFields != null) {
      Collections.copy(this.unknownFields, other.unknownFields);
    }
  }

  public Basic deepCopy() {
    return new Basic(this);
  }

  @Override
  public void clear() {
    this.alphabet = null;
    this.unknownFields.clear();
    this.unknownFields = null;
  }

  /**
   * 
   * @see Alphabet
   */
  public Alphabet getXAlphabet() {
    return this.alphabet;
  }

  /**
   * 
   * @see Alphabet
   */
  public Basic setXAlphabet(Alphabet alphabet) {
    this.alphabet = alphabet;
    return this;
  }

  public void unsetXAlphabet() {
    this.alphabet = null;
  }

  /** Returns true if field alphabet is set (has been assigned a value) and false otherwise */
  public boolean isSetXAlphabet() {
    return this.alphabet != null;
  }

  public void setXAlphabetIsSet(boolean value) {
    if (!value) {
      this.alphabet = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ALPHABET:
      if (value == null) {
        unsetXAlphabet();
      } else {
        setXAlphabet((Alphabet)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ALPHABET:
      return getXAlphabet();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ALPHABET:
      return isSetXAlphabet();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Basic)
      return this.equals((Basic)that);
    return false;
  }

  public boolean equals(Basic that) {
    if (that == null)
      return false;

    boolean this_present_alphabet = true && this.isSetXAlphabet();
    boolean that_present_alphabet = true && that.isSetXAlphabet();
    if (this_present_alphabet || that_present_alphabet) {
      if (!(this_present_alphabet && that_present_alphabet))
        return false;
      if (!this.alphabet.equals(that.alphabet))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_alphabet = true && (isSetXAlphabet());
    builder.append(present_alphabet);
    if (present_alphabet)
      builder.append(alphabet.getValue());

    return builder.toHashCode();
  }

  public int compareTo(Basic other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Basic typedOther = (Basic)other;

    lastComparison = Boolean.valueOf(isSetXAlphabet()).compareTo(typedOther.isSetXAlphabet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXAlphabet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.alphabet, typedOther.alphabet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // ALPHABET
          if (field.type == org.apache.thrift.protocol.TType.I32) {
            this.alphabet = Alphabet.findByValue(iprot.readI32());
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          if (field.id > 1) {
            com.mediav.thrift.TData unknownField = com.mediav.thrift.TProtocolUtils.read(iprot, field);
            if (unknownFields == null) {
              unknownFields = new LinkedList<com.mediav.thrift.TData>();
            }
            unknownFields.add(unknownField);
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.alphabet != null) {
      oprot.writeFieldBegin(ALPHABET_FIELD_DESC);
      oprot.writeI32(this.alphabet.getValue());
      oprot.writeFieldEnd();
    }
    for (com.mediav.thrift.TData unknownField : unknownFields) {
      oprot.writeFieldBegin(unknownField.gettField());
      com.mediav.thrift.TProtocolUtils.write(oprot, unknownField);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("XBasic(");
    boolean first = true;

    sb.append("alphabet:");
    if (this.alphabet == null) {
      sb.append("null");
    } else {
      sb.append(this.alphabet);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (alphabet == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'alphabet' was not present! Struct: " + toString());
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

